# Algebra (cebir)

In [19]:
from IPython.display import Math,display
import sympy as sym
x = sym.symbols('x')
denk= sym.Eq(4*x + 14,9)# 2x+4 = 9 anlaminadir eq esiitir anlamindadir
sol = sym.solve(denk,x)# solve ile denklemi cozduk ve x yerine 5/2 getirecek
display(Math(f'{sym.latex(denk)} \\\\  \\text{{denkleminin cozum kumesi yani x yerine gelecek olan deger}}  {sol}'))
sym.solve(4*x **2 +5 )

<IPython.core.display.Math object>

[-sqrt(5)*I/2, sqrt(5)*I/2]

In [ ]:
#1 ornek
q = sym.symbols('q')
eq = 3*q + 4/q + 3 - 5*q - 1/q - 1
display(eq)
display(Math(sym.latex(eq)))
display(Math(f'g = {sym.latex(sym.solve(eq,q))}')) # cozum kumesini verecek


-2*q + 2 + 3/q

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [ ]:
#2
eq2 = 2*q + 3*q**2 - 5/q - 4/q**3
display(eq2)
display(Math(sym.latex(sym.simplify(eq2))))
display(Math(f'q= {sym.latex(sym.solve(eq2,q))}'))#CRootOf, denklemin köklerini sembolik olarak temsil ediyor
display(Math(f'q= {sym.latex(sym.cancel(eq2,q))}')) # cancel butunsel bir sadelestirme ornegi sunar bize



3*q**2 + 2*q - 5/q - 4/q**3

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [ ]:
import sympy as sym
'''
for index, deger in enumerate(liste):enumerate kullanimi
    # index → 0, 1, 2, ...
    # deger → liste[0], liste[1], liste[2], ...

    '''
x = sym.symbols('x')
denklem = 3*x**5 + 2*x**4 - 5*x**2 - 4

# Kökleri bul
cozumler = sym.solve(denklem, x)

print("Sembolik temsil:")
for i, cozum in enumerate(cozumler):
    print(f"Kök {i}: {cozum}")

print("\nSayısal değerleri:")
for i, cozum in enumerate(cozumler):
    sayisal_deger = cozum.evalf()  # Sayısal değere çevir
    print(f"Kök {i}: {sayisal_deger}")

Sembolik temsil:
Kök 0: CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 0)
Kök 1: CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 1)
Kök 2: CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 2)
Kök 3: CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 3)
Kök 4: CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 4)

Sayısal değerleri:
Kök 0: 1.18716560776318
Kök 1: -0.994074543510897 - 0.936886436711566*I
Kök 2: -0.994074543510897 + 0.936886436711566*I
Kök 3: 0.0671584062959738 - 0.772914692708164*I
Kök 4: 0.0671584062959738 + 0.772914692708164*I


In [39]:
# Expanding terms (islem genisletme)
#dagilma ozelligini a(a+b) = a^2+ab seklinde

x = sym.symbols('x')
term1 = 4*x + 20
term2 = x + 6
term3 = x
display(Math(f'{sym.latex(term1*term2)} = {sym.latex(sym.expand(term1*term2))}'))

<IPython.core.display.Math object>

In [ ]:
from sympy.abc import x,y 
Fxy = (6+x)*(4-y)
for ix in range(0,4):
    for iy in range(0,4):
        print(f'her x= {ix} ve y={iy}, f(x,y)= {Fxy.subs({x:ix,y:iy})}')# subs denklemde yerine koymak istedgimiz degiskenin yerine sayi koymak icin
#Fxy.subs({x:1,y:0})# sozluk tanimi yaptik subs degisken yerine sayi koy isine yariyor


her x= 0 ve y=0, f(x,y)= 24
her x= 0 ve y=1, f(x,y)= 18
her x= 0 ve y=2, f(x,y)= 12
her x= 0 ve y=3, f(x,y)= 6
her x= 1 ve y=0, f(x,y)= 28
her x= 1 ve y=1, f(x,y)= 21
her x= 1 ve y=2, f(x,y)= 14
her x= 1 ve y=3, f(x,y)= 7
her x= 2 ve y=0, f(x,y)= 32
her x= 2 ve y=1, f(x,y)= 24
her x= 2 ve y=2, f(x,y)= 16
her x= 2 ve y=3, f(x,y)= 8
her x= 3 ve y=0, f(x,y)= 36
her x= 3 ve y=1, f(x,y)= 27
her x= 3 ve y=2, f(x,y)= 18
her x= 3 ve y=3, f(x,y)= 9


## Matrisler

In [1]:
from IPython.display import display,Math
import numpy as np
import sympy as sym


In [10]:
N = np.array([[1,2],[3,4]])
type(N)
display(Math(sym.latex(sym.simplify(N))))

<IPython.core.display.Math object>

In [33]:
import numpy as np

# 5x6'lık matris oluştur
create_matrix = np.zeros([5, 6])

# Manuel değer atamaları
create_matrix[0, 5] = 4  # 1. satır, 6. sütun
create_matrix[1, 3] = 7  # 2. satır, 4. sütun

print("Manuel atamadan sonra:")
print(create_matrix)

# Matematiksel desen oluştur
for satir in range(5):      # 0'dan 4'e kadar
    for sutun in range(6):  # 0'dan 5'e kadar
        # (-1)^(satir+sutun) → +1 veya -1
        create_matrix[satir, sutun] = (-1) ** (satir + sutun)

print("\nMatematiksel desen uygulandıktan sonra:")
print(create_matrix)

Manuel atamadan sonra:
[[0. 0. 0. 0. 0. 4.]
 [0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Matematiksel desen uygulandıktan sonra:
[[ 1. -1.  1. -1.  1. -1.]
 [-1.  1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1. -1.]
 [-1.  1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1. -1.]]


In [40]:
x,y = sym.symbols('x,y')
fxy = (6-x)*(3+y)
xsets = range(0,4)
ysets = range(0,4)
xymatris = np.zeros([len(xsets),len(ysets)])

for i in xsets:
    for j in ysets:
        xymatris[i,j] = fxy.subs({x:i,y:j})
display(Math(sym.latex(sym.simplify(xymatris))))# gercek bir matris goruntusu elde edelim

<IPython.core.display.Math object>

In [ ]:
x,y = sym.symbols('x,y')
xsets = range(1,11)
ysets = range(1,11)
xymatris = np.zeros([len(xsets),len(ysets)],dtype=int)# xsets satirlari ysets sutunlari
for i in xsets:
    for j in ysets:
        xymatris[i-1,j-1] = i * j

display(Math(sym.latex(sym.simplify(xymatris))))

<IPython.core.display.Math object>

In [6]:
# use sympy to expand and simplify these expressions
import sympy as sym
from IPython.display import Math,display

x = sym.symbols('x')

e1 = 2*x + x*(4-6*x) + x
e2 = -x * (2/x + 4/(x**2)) + (4+x)/(4*x)
e3 = (x + 3)*(x-3)*x*(1/(9*x))

# make a list of the expressions
exprs = [e1,e2,e3]

for i, expr in enumerate(exprs):
    display(Math(f'{sym.latex(expr)} \\quad \\Rightarrow \\quad {sym.latex(sym.expand(expr))}'))
   

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [7]:
import sympy as sym
from IPython.display import Math, display

x = sym.symbols('x')

e1 = 2*x + x*(4-6*x) + x
e2 = -x * (2/x + 4/(x**2)) + (4+x)/(4*x)
e3 = (x + 3)*(x-3)*x*(1/(9*x))

exprs = [e1, e2, e3]

for i, expr in enumerate(exprs, 1):
    genisletilmis = sym.expand(expr)
    basitlestirilmis = sym.simplify(expr)
    
    display(Math(f'\\text{{İfade {i}:}}'))
    display(Math(f'{sym.latex(expr)}'))
    display(Math(f'\\text{{Genişletilmiş: }}{sym.latex(genisletilmis)}'))
    display(Math(f'\\text{{Basitleştirilmiş: }}{sym.latex(basitlestirilmis)}'))
    print("\\n" + "="*50 + "\\n")

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

\n==================================================\n


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

\n==================================================\n


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

\n==================================================\n


In [23]:
#liste[baslangic:bitis:adim]
'''
başlangıç: dahil (varsayılan: 0)

bitiş: dahil DEĞİL (varsayılan: son)

adım: atlama sayısı (varsayılan: 1)'''

liste = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print("Orjinal liste:", liste)
print("liste[2:5]:", liste[2:5])      # [2, 3, 4]
print("liste[:4]:", liste[:4])        # [0, 1, 2, 3] 
print("liste[6:]:", liste[6:])        # [6, 7, 8, 9]
print("liste[::2]:", liste[::2])      # [0, 2, 4, 6, 8] - 2şer atla
print("liste[::-1]:", liste[::-1])    # [9, 8, 7, 6, 5, 4, 3, 2, 1, 0] - ters çevir



# 2 Ornek
sayilar = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

# İlk 5 eleman
print("İlk 5:", sayilar[:5])          # [10, 20, 30, 40, 50]

# Son 3 eleman  
print("Son 3:", sayilar[-3:])         # [80, 90, 100]

# 3'ten 7'ye kadar (7 dahil değil)
print("3-7:", sayilar[3:7])           # [40, 50, 60, 70]

# 2şer atlayarak
print("2şer atla:", sayilar[::2])     # [10, 30, 50, 70, 90]



# 3 string listesi ile verelim
meyveler = ["elma", "armut", "çilek", "muz", "portakal", "kiraz"]

print("İlk 2 meyve:", meyveler[:2])        # ['elma', 'armut']
print("Son 2 meyve:", meyveler[-2:])       # ['portakal', 'kiraz']
print("Ortadaki 3:", meyveler[1:4])        # ['armut', 'çilek', 'muz']
print("Ters sıra:", meyveler[::-1])        # ['kiraz', 'portakal', 'muz', 'çilek', 'armut', 'elma']

# 4  ADIM (STEP) KULLANIMI:
sayilar = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print("2şer atla:", sayilar[::2])         # [0, 2, 4, 6, 8]
print("3er atla:", sayilar[::3])          # [0, 3, 6, 9]
print("Ters 2şer:", sayilar[::-2])        # [9, 7, 5, 3, 1]
print("Belirli aralıkta 2şer:", sayilar[1:8:2])  # [1, 3, 5, 7]


# 5 Matris Islemi olarak 
matris = [
    [1, 2, 3, 4],
    [5, 6, 7, 8], 
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

print("Her satırın ilk 2 elemanı:")
for satir_no, satir in enumerate(matris, 1):  # 1'den başla
    print(f'{satir_no}. satır: {satir[:3]}') # her satirin 3 elemani

Orjinal liste: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
liste[2:5]: [2, 3, 4]
liste[:4]: [0, 1, 2, 3]
liste[6:]: [6, 7, 8, 9]
liste[::2]: [0, 2, 4, 6, 8]
liste[::-1]: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
İlk 5: [10, 20, 30, 40, 50]
Son 3: [80, 90, 100]
3-7: [40, 50, 60, 70]
2şer atla: [10, 30, 50, 70, 90]
İlk 2 meyve: ['elma', 'armut']
Son 2 meyve: ['portakal', 'kiraz']
Ortadaki 3: ['armut', 'çilek', 'muz']
Ters sıra: ['kiraz', 'portakal', 'muz', 'çilek', 'armut', 'elma']
2şer atla: [0, 2, 4, 6, 8]
3er atla: [0, 3, 6, 9]
Ters 2şer: [9, 7, 5, 3, 1]
Belirli aralıkta 2şer: [1, 3, 5, 7]
Her satırın ilk 2 elemanı:
1. satır: [1, 2, 3]
2. satır: [5, 6, 7]
3. satır: [9, 10, 11]
4. satır: [13, 14, 15]


In [47]:
import numpy as np
matris = np.zeros([4,3])
sayac = 0

for i in range(4):
    for j in range(3):
        matris[i,j] = sayac
        sayac += 2
matris  
  

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.]])

### Ebob ekok

In [ ]:
import math
from IPython.display import display, Math

x = 120
y = 80

# Önce EBOB'u doğru hesapla
ebob = math.gcd(x, y)

# Doğru formül: x/y = (x/ebob) / (y/ebob)
display(Math(f'\\frac{{{x}}}{{{y}}} \\quad = \\quad \\frac{{{x} \\div {ebob}}}{{{y} \\div {ebob}}} \\quad = \\quad \\frac{{{x//ebob}}}{{{y//ebob}}}'))#\div =  ÷ klasik bolme islemi


<IPython.core.display.Math object>